# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\x12\x07request\"\x1f\n\rHeaderContent\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xa9\x01\n\x07Request\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12,\n\x06header\x18\x03 \x03(\x0b\x32\x1c.request.Request.HeaderEntry\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x1a\x45\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.request.HeaderContent:\x02\x38\x01\x42\x13Z\x11http-perf/requestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021http-perf/request'
  _REQUEST_HEADERENTRY._options = None
  _REQUEST_HEADERENTRY._serialized_options = b'8\001'
  _globals['_HEADERCONTENT']._serialized_start=26
  _globals['_HEADERCONTENT']._serialized_end=57
  _globals['_REQUEST']._serialized_start=60
  _globals['_REQUEST']._serialized_end=229
  _globals['_REQUEST_HEADERENTRY']._serialized_start=160
  _globals['_REQUEST_HEADERENTRY']._serialized_end=229
# @@protoc_insertion_point(module_scope)
